[package]
name = "wayang-rs"
version = "0.1.0"
authors = ["Adityo Pratomo <pratomo.adityo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
yarte = "0.10"
